# Configuration latexmk pour les diapos STT-1920
$pdf_mode = 1;                       # pdflatex
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex_use = 1.5;                   # biber seulement si un .bib est utilisé
$clean_ext = 'nav snm vrb bbl run.xml';   # fichiers propres à Beamer et biblatex
